onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - jpegtran-bin
  - mozjpeg
  - sharp
  - unrs-resolver

overrides:
  cloudinary@<2.7.0: '>=2.7.0'
  cross-spawn@<6.0.6: '>=6.0.6'
  got@<11.8.5: '>=11.8.5'
  http-cache-semantics@<4.1.1: '>=4.1.1'
  semver-regex@<3.1.3: '>=3.1.3'
  semver-regex@<3.1.4: '>=3.1.4'
  trim-newlines@<3.0.1: '>=3.0.1'
